# Generated by Django 3.2.6 on 2021-08-22 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="namn")),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="namn")),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="företagsnamn"),
                ),
                (
                    "organisation_number",
                    models.CharField(
                        max_length=100, verbose_name="organisationsnummer"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(verbose_name="beskrivning")),
                ("image", models.ImageField(upload_to="producer-images")),
                ("categories", models.ManyToManyField(to="producer.Category")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="producer.producer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_option",
                    models.CharField(
                        choices=[
                            ("swish", "Swish"),
                            ("card", "Kortbetalning"),
                            ("cash", "Kontant"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="producer.producer",
                    ),
                ),
            ],
        ),
    ]
