# Generated by Django 5.2.5 on 2025-12-28 20:11

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="namn")),
                ("address", models.CharField(blank=True, max_length=100, verbose_name="adress")),
                ("description", models.TextField(blank=True, verbose_name="beskrivning")),
                ("link", models.URLField(blank=True, verbose_name="länk till plats")),
            ],
            options={
                "verbose_name": "plats",
                "verbose_name_plural": "platser",
            },
        ),
        migrations.CreateModel(
            name="Pickup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="datum")),
                ("start_time", models.TimeField(verbose_name="starttid")),
                ("end_time", models.TimeField(verbose_name="sluttid")),
                ("is_published", models.BooleanField(verbose_name="är publicerad")),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="reko.location", verbose_name="plats"
                    ),
                ),
            ],
            options={
                "verbose_name": "utlämningsplats",
                "verbose_name_plural": "utlämningsplatser",
            },
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(max_length=100, verbose_name="visningsnamn")),
                ("company_name", models.CharField(max_length=100, verbose_name="företagsnamn")),
                ("slug", models.SlugField(help_text="Används för att generera din unika länk.", unique=True)),
                ("phone", models.CharField(max_length=50, verbose_name="telefonnummer")),
                ("email", models.EmailField(max_length=254, verbose_name="mejladress")),
                (
                    "swish_number",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(123|07[0-9])[0-9]{7}$", message="Ange ett giltigt Swishnummer."
                            )
                        ],
                        verbose_name="swishnummer",
                    ),
                ),
                ("address", models.CharField(max_length=100, verbose_name="adress")),
                ("description", models.TextField(verbose_name="beskrivning")),
                ("image", models.ImageField(upload_to="producer-images", verbose_name="bild")),
                (
                    "color_palette",
                    models.CharField(
                        choices=[
                            ("red", "Röd"),
                            ("orange", "Orange"),
                            ("yellow", "Gul"),
                            ("green", "Grön"),
                            ("cyan", "Cyan"),
                            ("blue", "Blå"),
                            ("indigo", "Indigo"),
                            ("purple", "Lila"),
                            ("pink", "Rosa"),
                            ("gray", "Grå"),
                        ],
                        verbose_name="färgpalett",
                    ),
                ),
                ("pickups", models.ManyToManyField(to="reko.pickup", verbose_name="utlämningsplatser")),
            ],
            options={
                "verbose_name": "producent",
                "verbose_name_plural": "producenter",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_number", models.PositiveIntegerField(verbose_name="#")),
                ("name", models.CharField(max_length=100, verbose_name="namn")),
                ("email", models.EmailField(max_length=254, verbose_name="mejladress")),
                ("phone", models.CharField(max_length=50, verbose_name="telefonnummer")),
                ("note", models.TextField(blank=True, verbose_name="anteckning")),
                (
                    "pickup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reko.pickup", verbose_name="utlämningsplats"
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reko.producer", verbose_name="producent"
                    ),
                ),
            ],
            options={
                "verbose_name": "beställning",
                "verbose_name_plural": "beställningar",
                "unique_together": {("producer", "order_number")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="namn")),
                ("image", models.ImageField(upload_to="", verbose_name="bild")),
                (
                    "price_with_vat",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ange priset inklusive moms.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="pris",
                    ),
                ),
                (
                    "vat_factor",
                    models.DecimalField(
                        choices=[
                            (Decimal("0.0000"), "0\xa0% (momsfri)"),
                            (Decimal("0.0600"), "6\xa0%"),
                            (Decimal("0.1200"), "12\xa0%"),
                            (Decimal("0.2500"), "25\xa0%"),
                        ],
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="momssats",
                    ),
                ),
                ("is_published", models.BooleanField(default=True, verbose_name="är publicerad")),
                ("description", models.TextField(verbose_name="beskrivning")),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reko.producer", verbose_name="producent"
                    ),
                ),
            ],
            options={
                "verbose_name": "produkt",
                "verbose_name_plural": "produkter",
            },
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="namn")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="antal",
                    ),
                ),
                (
                    "price_with_vat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="pris",
                    ),
                ),
                ("vat_factor", models.DecimalField(decimal_places=4, max_digits=5, verbose_name="momssats")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reko.order")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="reko.product", verbose_name="produkt"
                    ),
                ),
            ],
            options={
                "verbose_name": "produkt",
                "verbose_name_plural": "produkter",
            },
        ),
        migrations.CreateModel(
            name="Ring",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(verbose_name="namn")),
                ("producers", models.ManyToManyField(to="reko.producer", verbose_name="producenter")),
            ],
            options={
                "verbose_name": "ring",
                "verbose_name_plural": "ringar",
            },
        ),
        migrations.AddField(
            model_name="pickup",
            name="ring",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="reko.ring"),
        ),
        migrations.AddField(
            model_name="location",
            name="ring",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="reko.ring"),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="mejladress")),
                ("is_active", models.BooleanField(verbose_name="är aktiv")),
                ("is_superuser", models.BooleanField(verbose_name="är superadmin")),
                ("producers", models.ManyToManyField(blank=True, to="reko.producer", verbose_name="producenter")),
                ("rings", models.ManyToManyField(blank=True, to="reko.ring", verbose_name="ringar")),
            ],
            options={
                "verbose_name": "användare",
                "verbose_name_plural": "användare",
            },
        ),
    ]
