# Generated by Django 5.0.10 on 2025-01-19 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="mejladress")),
                ("is_active", models.BooleanField(verbose_name="är aktiv")),
                ("is_superuser", models.BooleanField(verbose_name="är superadmin")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=100, verbose_name="plats")),
                ("date", models.DateField(verbose_name="datum")),
                ("start_time", models.TimeField(verbose_name="starttid")),
                ("end_time", models.TimeField(verbose_name="sluttid")),
                ("link", models.URLField(blank=True, verbose_name="länk till utlämningsplats")),
                ("is_published", models.BooleanField()),
            ],
            options={
                "verbose_name": "utlämningsplats",
                "verbose_name_plural": "utlämningsplatser",
            },
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(max_length=100, verbose_name="visningsnamn")),
                ("company_name", models.CharField(max_length=100, verbose_name="företagsnamn")),
                ("slug", models.SlugField(help_text="Används för att generera din unika länk.", unique=True)),
                ("phone", models.CharField(max_length=50, verbose_name="telefonnummer")),
                ("email", models.EmailField(max_length=254, verbose_name="mejladress")),
                ("swish_number", models.CharField(max_length=50, verbose_name="swishnummer")),
                ("address", models.CharField(max_length=100, verbose_name="adress")),
                ("description", models.TextField(verbose_name="beskrivning")),
                ("image", models.ImageField(upload_to="producer-images", verbose_name="bild")),
            ],
            options={
                "verbose_name": "producent",
                "verbose_name_plural": "producenter",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_number", models.PositiveIntegerField(verbose_name="#")),
                ("name", models.CharField(max_length=100, verbose_name="namn")),
                ("email", models.EmailField(max_length=254, verbose_name="mejladress")),
                ("phone", models.CharField(max_length=50, verbose_name="telefonnummer")),
                ("note", models.TextField(blank=True, verbose_name="anteckning")),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reko.location", verbose_name="utlämningsplats"
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reko.producer", verbose_name="producent"
                    ),
                ),
            ],
            options={
                "verbose_name": "beställning",
                "verbose_name_plural": "beställningar",
                "unique_together": {("producer", "order_number")},
            },
        ),
        migrations.AddField(
            model_name="location",
            name="producer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reko.producer", verbose_name="producent"
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="namn")),
                ("image", models.ImageField(upload_to="", verbose_name="bild")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="pris")),
                ("is_published", models.BooleanField(default=True, verbose_name="är publicerad")),
                ("description", models.TextField(verbose_name="beskrivning")),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reko.producer", verbose_name="producent"
                    ),
                ),
            ],
            options={
                "verbose_name": "produkt",
                "verbose_name_plural": "produkter",
            },
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="namn")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="antal")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="pris")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reko.order")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="reko.product", verbose_name="produkt"
                    ),
                ),
            ],
            options={
                "verbose_name": "produkt",
                "verbose_name_plural": "produkter",
            },
        ),
    ]
