# Generated by Django 5.0.10 on 2025-01-25 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reko", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Location",
            new_name="Pickup",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="location",
            new_name="pickup",
        ),
    ]
