# Generated by Django 5.0.10 on 2025-01-18 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reko", "0002_remove_product_items_in_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="mejladress"),
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=100, verbose_name="namn"),
        ),
        migrations.AlterField(
            model_name="order",
            name="note",
            field=models.TextField(blank=True, verbose_name="anteckning"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.PositiveIntegerField(verbose_name="#"),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=50, verbose_name="telefonnummer"),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="antal"),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="name",
            field=models.CharField(max_length=100, verbose_name="namn"),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="pris"),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="reko.product", verbose_name="produkt"
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="mejladress"),
        ),
        migrations.AlterField(
            model_name="product",
            name="producer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reko.producer", verbose_name="producent"
            ),
        ),
    ]
