# Generated by Django 5.0.10 on 2025-01-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reko", "0002_rename_location_pickup_rename_location_order_pickup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ring",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(verbose_name="namn")),
                ("producers", models.ManyToManyField(to="reko.producer", verbose_name="producenter")),
            ],
            options={
                "verbose_name": "ring",
                "verbose_name_plural": "ringar",
            },
        ),
    ]
