# Generated by Django 5.0.11 on 2025-03-22 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reko", "0004_alter_user_options_user_producers_user_rings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pickup",
            name="producer",
        ),
        migrations.AddField(
            model_name="pickup",
            name="ring",
            field=models.ForeignKey(default=123241, on_delete=django.db.models.deletion.PROTECT, to="reko.ring"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producer",
            name="pickups",
            field=models.ManyToManyField(to="reko.pickup"),
        ),
    ]
