# Generated by Django 5.0.10 on 2025-01-18 15:49
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reko", "0005_alter_location_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="end_time",
            field=models.TimeField(verbose_name="sluttid"),
        ),
        migrations.AddField(
            model_name="location",
            name="start_time",
            field=models.TimeField(verbose_name="starttid"),
        ),
    ]
