# Generated by Django 5.0.10 on 2025-01-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reko", "0006_location_end_time_location_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producer",
            name="name",
        ),
        migrations.AddField(
            model_name="producer",
            name="company_name",
            field=models.CharField(default="", max_length=100, verbose_name="företagsnamn"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producer",
            name="display_name",
            field=models.CharField(default="", max_length=100, verbose_name="visningsnamn"),
            preserve_default=False,
        ),
    ]
