name: Backend
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup pip/poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.1.0
      - name: .venv cache
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('pyproject.toml', 'poetry.lock') }}-v2
      - name: Install venv dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          poetry install
        run: poetry run mypy --strict --strict-equality src
